// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "munkeyking":return img`
................................................................
...................................ff....ff.....................
...........................ff......fff..fff...f.................
...........................f5ff...f55ffff5fffff.................
...........................f555ffff555ff555ff5f.................
...........................ff555ff555555555555f.................
............................f5555557777555555f..................
............................f5522557777552255f..................
............................ff52255555555225ff..................
..........................fffff555555555555ffefff...............
..........................fffefffffffffffffffefff...............
..........................fffeeeeeeeeeeeeeeeeefff...............
.......................fffeeeeeeeeeedddddddddddddffff...........
.......................fffeeeeeeeeeedddddddddddddffff...........
.......................fffeeeeeeeeeedddddddddddddffff...........
...................fffffffeeeeeeedddfffdddddddfffddddccc........
...................fffffffeeeeeeedddfffdddddddfffddddccc........
...................fffffffeeeeeeedddfffdddddddfffddddccc........
...................fffffffeeeeeeedddfffdddddddfffddddccc........
................fffdddddddeeeeeeedddfffdddddddfffddddccc........
................fffdddddddeeeeeeedddfffdddddddfffddddccc........
................fffdddddddeeeeeeedddfffdddddddfffddddccc........
................cccddddbbbeeeeeeedddddddddddddeeeeeeedddccc.....
................cccddddbbbeeeeeeedddddddddddddeeeeeeedddccc.....
................cccddddbbbeeeeeeedddddddddddddeeeeeeedddccc.....
.........ffff...cccddddbbbeeeeeeeddddddccccdddddddddddddccc.....
.........ffff...cccddddbbbeeeeeeeddddddccccdddddddddddddccc.....
.........ffff...cccddddbbbeeeeeeeddddddccccdddddddddddddccc.....
......fffeeeefff...ccccfffeeeeeeeddddddddddcccccccccccccccc.....
......fffeeeefff...ccccfffeeeeeeeddddddddddcccccccccccccccc.....
......fffeeeefff...ccccfffeeeeeeeddddddddddcccccccccccccccc.....
......fffeeeefff.......ffffffeeeeeeedddddddddddddddddfff........
......fffeeeefff.......ffffffeeeeeeedddddddddddddddddfff........
......fffeeeefff.......ffffffeeeeeeedddddddddddddddddfff........
......fffeeeefff.......ffffffeeeeeeedddddddddddddddddfff........
......fffeeeefff.......ffffffeeeeeeedddddddddddddddddfff........
......fffeeeefff...ffffeeeeeeeeeeeeefffffffffffffffff...........
......fffeeeefff...ffffeeeeeeeeeeeeefffffffffffffffff...........
......fffeeeefff...ffffeeeeeeeeeeeeefffffffffffffffff...........
......fffeeeeffffffeeeeeeeeeeeeeeeeeeeeeeeefff..................
......fffeeeeffffffeeeeeeeeeeeeeeeeeeeeeeeefff..................
......fffeeeeffffffeeeeeeeeeeeeeeeeeeeeeeeefff..................
......fffeeeeffffffeeeeeeeeeeeeeeeeeeeeeeeefff..................
.........fffffffeeeeeeeeeeeeeffffeeefffffffeeefff...............
.........fffffffeeeeeeeeeeeeeffffeeefffffffeeefff...............
.........fffffffeeeeeeeeeeeeeffffeeefffffffeeefff...............
.............fffeeeeeeeeeeeeeffffeeefffffffeeefff...............
.............fffeeeeeeeeeeeeeffffeeefffffffeeefff...............
.............fffeeeeeeeeeeeeeffffeeefffffffeeefff...............
................fffeeeeffffffbbbbdddfffbbbbdddfff...............
................fffeeeeffffffbbbbdddfffbbbbdddfff...............
................fffeeeeffffffbbbbdddfffbbbbdddfff...............
................fffddddbbbbbbdddddddcccdddddddfff...............
................fffddddbbbbbbdddddddcccdddddddfff...............
................fffddddbbbbbbdddddddcccdddddddfff...............
................ffffffffffffffffffffffffffffff..................
................ffffffffffffffffffffffffffffff..................
................ffffffffffffffffffffffffffffff..................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
            case "?J`[0*OBsNA":
            case "bigmunky":return img`
..........................................fffffffffffffffffffffffffffffff.......................
..........................................fffffffffffffffffffffffffffffff.......................
..........................................fffffffffffffffffffffffffffffff.......................
..........................................fffffffffffffffffffffffffffffff.......................
...................................fffffffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefffffff................
...................................fffffffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefffffff................
...................................fffffffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefffffff................
...................................fffffffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefffffff................
...................................fffffffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefffffff................
...................................fffffffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefffffff................
............................fffffffeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddfffffff.........
............................fffffffeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddfffffff.........
............................fffffffeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddfffffff.........
............................fffffffeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddfffffff.........
............................fffffffeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddfffffff.........
............................fffffffeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddfffffff.........
......................fffffffffffffeeeeeeeeeeeeddddddfffffffdddddddddddddfffffffdddddddcccccc...
......................fffffffffffffeeeeeeeeeeeeddddddfffffffdddddddddddddfffffffdddddddcccccc...
......................fffffffffffffeeeeeeeeeeeeddddddfffffffdddddddddddddfffffffdddddddcccccc...
......................fffffffffffffeeeeeeeeeeeeddddddfffffffdddddddddddddfffffffdddddddcccccc...
......................fffffffffffffeeeeeeeeeeeeddddddfffffffdddddddddddddfffffffdddddddcccccc...
......................fffffffffffffeeeeeeeeeeeeddddddfffffffdddddddddddddfffffffdddddddcccccc...
...............fffffffdddddddddddddeeeeeeeeeeeeddddddfffffffdddddddddddddfffffffdddddddcccccc...
...............fffffffdddddddddddddeeeeeeeeeeeeddddddfffffffdddddddddddddfffffffdddddddcccccc...
...............fffffffdddddddddddddeeeeeeeeeeeeddddddfffffffdddddddddddddfffffffdddddddcccccc...
...............fffffffdddddddddddddeeeeeeeeeeeeddddddfffffffdddddddddddddfffffffdddddddcccccc...
...............fffffffdddddddddddddeeeeeeeeeeeeddddddfffffffdddddddddddddfffffffdddddddcccccc...
...............fffffffdddddddddddddeeeeeeeeeeeeddddddfffffffdddddddddddddfffffffdddddddcccccc...
...............cccccccddddddbbbbbbbeeeeeeeeeeeeddddddddddddddddddddddddddeeeeeeeeeeeeeeddddddccc
...............cccccccddddddbbbbbbbeeeeeeeeeeeeddddddddddddddddddddddddddeeeeeeeeeeeeeeddddddccc
...............cccccccddddddbbbbbbbeeeeeeeeeeeeddddddddddddddddddddddddddeeeeeeeeeeeeeeddddddccc
...............cccccccddddddbbbbbbbeeeeeeeeeeeeddddddddddddddddddddddddddeeeeeeeeeeeeeeddddddccc
...............cccccccddddddbbbbbbbeeeeeeeeeeeeddddddddddddddddddddddddddeeeeeeeeeeeeeeddddddccc
...............cccccccddddddbbbbbbbeeeeeeeeeeeeddddddddddddddddddddddddddeeeeeeeeeeeeeeddddddccc
...............cccccccddddddbbbbbbbeeeeeeeeeeeeddddddddddddddddddddddddddeeeeeeeeeeeeeeddddddccc
ffffffff.......cccccccddddddbbbbbbbeeeeeeeeeeeedddddddddddddcccccccddddddddddddddddddddddddddccc
ffffffff.......cccccccddddddbbbbbbbeeeeeeeeeeeedddddddddddddcccccccddddddddddddddddddddddddddccc
ffffffff.......cccccccddddddbbbbbbbeeeeeeeeeeeedddddddddddddcccccccddddddddddddddddddddddddddccc
ffffffff.......cccccccddddddbbbbbbbeeeeeeeeeeeedddddddddddddcccccccddddddddddddddddddddddddddccc
ffffffff.......cccccccddddddbbbbbbbeeeeeeeeeeeedddddddddddddcccccccddddddddddddddddddddddddddccc
ffffffff.......cccccccddddddbbbbbbbeeeeeeeeeeeedddddddddddddcccccccddddddddddddddddddddddddddccc
ffeeeeeefffffff.......ccccccfffffffeeeeeeeeeeeeddddddddddddddddddddccccccccccccccccccccccccccccc
ffeeeeeefffffff.......ccccccfffffffeeeeeeeeeeeeddddddddddddddddddddccccccccccccccccccccccccccccc
ffeeeeeefffffff.......ccccccfffffffeeeeeeeeeeeeddddddddddddddddddddccccccccccccccccccccccccccccc
ffeeeeeefffffff.......ccccccfffffffeeeeeeeeeeeeddddddddddddddddddddccccccccccccccccccccccccccccc
ffeeeeeefffffff.......ccccccfffffffeeeeeeeeeeeeddddddddddddddddddddccccccccccccccccccccccccccccc
ffeeeeeefffffff.......ccccccfffffffeeeeeeeeeeeeddddddddddddddddddddccccccccccccccccccccccccccccc
ffeeeeeefffffff.............ffffffffffffffeeeeeeeeeeeddddddddddddddddddddddddddddddddddffffff...
ffeeeeeefffffff.............ffffffffffffffeeeeeeeeeeeddddddddddddddddddddddddddddddddddffffff...
ffeeeeeefffffff.............ffffffffffffffeeeeeeeeeeeddddddddddddddddddddddddddddddddddffffff...
ffeeeeeefffffff.............ffffffffffffffeeeeeeeeeeeddddddddddddddddddddddddddddddddddffffff...
ffeeeeeefffffff.............ffffffffffffffeeeeeeeeeeeddddddddddddddddddddddddddddddddddffffff...
ffeeeeeefffffff.............ffffffffffffffeeeeeeeeeeeddddddddddddddddddddddddddddddddddffffff...
ffeeeeeefffffff.......ffffffeeeeeeeeeeeeeeeeeeeeeeeeeffffffffffffffffffffffffffffffffff.........
ffeeeeeefffffff.......ffffffeeeeeeeeeeeeeeeeeeeeeeeeeffffffffffffffffffffffffffffffffff.........
ffeeeeeefffffff.......ffffffeeeeeeeeeeeeeeeeeeeeeeeeeffffffffffffffffffffffffffffffffff.........
ffeeeeeefffffff.......ffffffeeeeeeeeeeeeeeeeeeeeeeeeeffffffffffffffffffffffffffffffffff.........
ffeeeeeefffffff.......ffffffeeeeeeeeeeeeeeeeeeeeeeeeeffffffffffffffffffffffffffffffffff.........
ffeeeeeefffffff.......ffffffeeeeeeeeeeeeeeeeeeeeeeeeeffffffffffffffffffffffffffffffffff.........
ffeeeeeeffffffffffffffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeffffff.......................
ffeeeeeeffffffffffffffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeffffff.......................
ffeeeeeeffffffffffffffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeffffff.......................
ffeeeeeeffffffffffffffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeffffff.......................
ffeeeeeeffffffffffffffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeffffff.......................
ffeeeeeeffffffffffffffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeffffff.......................
ffeeeeeeffffffffffffffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeffffff.......................
..fffffffffffffeeeeeeeeeeeeeeeeeeeeeeeeeeefffffeeeeeeffffffffffffffeeeeeefffffff................
..fffffffffffffeeeeeeeeeeeeeeeeeeeeeeeeeeefffffeeeeeeffffffffffffffeeeeeefffffff................
..fffffffffffffeeeeeeeeeeeeeeeeeeeeeeeeeeefffffeeeeeeffffffffffffffeeeeeefffffff................
..fffffffffffffeeeeeeeeeeeeeeeeeeeeeeeeeeefffffeeeeeeffffffffffffffeeeeeefffffff................
..fffffffffffffeeeeeeeeeeeeeeeeeeeeeeeeeeefffffeeeeeeffffffffffffffeeeeeefffffff................
..fffffffffffffeeeeeeeeeeeeeeeeeeeeeeeeeeefffffeeeeeeffffffffffffffeeeeeefffffff................
........fffffffeeeeeeeeeeeeeeeeeeeeeeeeeeefffffeeeeeeffffffffffffffeeeeeefffffff................
........fffffffeeeeeeeeeeeeeeeeeeeeeeeeeeefffffeeeeeeffffffffffffffeeeeeefffffff................
........fffffffeeeeeeeeeeeeeeeeeeeeeeeeeeefffffeeeeeeffffffffffffffeeeeeefffffff................
........fffffffeeeeeeeeeeeeeeeeeeeeeeeeeeefffffeeeeeeffffffffffffffeeeeeefffffff................
........fffffffeeeeeeeeeeeeeeeeeeeeeeeeeeefffffeeeeeeffffffffffffffeeeeeefffffff................
........fffffffeeeeeeeeeeeeeeeeeeeeeeeeeeefffffeeeeeeffffffffffffffeeeeeefffffff................
...............fffffffeeeeeeffffffffffffffbbbbbddddddfffffffbbbbbbbddddddfffffff................
...............fffffffeeeeeeffffffffffffffbbbbbddddddfffffffbbbbbbbddddddfffffff................
...............fffffffeeeeeeffffffffffffffbbbbbddddddfffffffbbbbbbbddddddfffffff................
...............fffffffeeeeeeffffffffffffffbbbbbddddddfffffffbbbbbbbddddddfffffff................
...............fffffffeeeeeeffffffffffffffbbbbbddddddfffffffbbbbbbbddddddfffffff................
...............fffffffeeeeeeffffffffffffffbbbbbddddddfffffffbbbbbbbddddddfffffff................
...............fffffffddddddbbbbbbbbbbbbbbdddddddddddcccccccdddddddddddddfffffff................
...............fffffffddddddbbbbbbbbbbbbbbdddddddddddcccccccdddddddddddddfffffff................
...............fffffffddddddbbbbbbbbbbbbbbdddddddddddcccccccdddddddddddddfffffff................
...............fffffffddddddbbbbbbbbbbbbbbdddddddddddcccccccdddddddddddddfffffff................
...............fffffffddddddbbbbbbbbbbbbbbdddddddddddcccccccdddddddddddddfffffff................
...............fffffffddddddbbbbbbbbbbbbbbdddddddddddcccccccdddddddddddddfffffff................
...............ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.......................
...............ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.......................
...............ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.......................
...............ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.......................
...............ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.......................
...............ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.......................
`;
            case "image2":
            case "backrgound":return img`
dddddd111dddddddddddddddddddddddddddddd11dddddddddddddddddddddddddddddddd11dddddddddddddddddddddddddddddd111ddddddddddddddddddddddddddddddd111dddddddddddddddddd
dddddd111dddddddddddddddddddddddddddddd11dddddddddddddddddddddddddddddddd11dddddddddddddddddddddddddddddd111ddddddddddddddddddddddddddddddd111dddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddd...................................................................................................................................................ddddddd
1111dd...................................................................................................................................................ddbdddd
1111dd...................................................................................................................................................ddbdddd
1111dd...................................................................................................................................................ddbdddd
1111dd...................................................................................................................................................ddddddd
1111dd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
ddddbb...................................................................................................................................................ddddddd
ddddbb...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................dddddd1
dddddd...................................................................................................................................................dddddd1
dddddd...................................................................................................................................................bbdddd1
dddddd...................................................................................................................................................bbdddd1
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................dddbbbd
dddddd...................................................................................................................................................dddbbbd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
1111dd...................................................................................................................................................ddbdddd
1111dd...................................................................................................................................................ddddddd
1111dd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
ddddbb...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................dddddd1
dddddd...................................................................................................................................................bbdddd1
dddddd...................................................................................................................................................bbdddd1
dddddd...................................................................................................................................................bbdddd1
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
1111dd...................................................................................................................................................ddbdddd
1111dd...................................................................................................................................................ddbdddd
1111dd...................................................................................................................................................ddddddd
1111dd...................................................................................................................................................ddddddd
1111dd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
ddddbb...................................................................................................................................................ddddddd
ddddbb...................................................................................................................................................ddddddd
ddddbb...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................dddddd1
dddddd...................................................................................................................................................dddddd1
dddddd...................................................................................................................................................dddddd1
dddddd...................................................................................................................................................bbdddd1
dddddd...................................................................................................................................................bbdddd1
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................dddbbbd
dddddd...................................................................................................................................................dddbbbd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
1111dd...................................................................................................................................................ddbdddd
1111dd...................................................................................................................................................ddbdddd
1111dd...................................................................................................................................................ddddddd
1111dd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddd...................................................................................................................................................ddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddbbdddddddddddddddddddddddddddddddbbdddddddddddddddddddddddddddddddbbbdddddddddddddddddddddddddddddddbdddddddddddddddddddddddddddddddbbbddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
`;
            case "tfLcmj3IyM@!1]A0)}b0":
            case "map":return img`
a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a 
a d d a d d d a d d d a d d d a d d d a d d d a d d d a d d 5 5 
d d d d d d d a d d d d d d d a d d d d d d d a d d d d d d 5 5 
d d d d d d d a d d d d d d d a d d d d d d d a d d d d d d 5 5 
d d d a d d d d d d d a d d d d d d d a d d d d d d d a d d 5 5 
d d d a d d d d d d d a d d d d d d d a d d d d d d d a d d 5 5 
a d d a d d d a d d d a d d d a d d d a d d d a d d d a d d 5 5 
a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a 
`;
            case "image3":
            case "munkey king":return img`
................
................
.....ff.ff.ff...
....f55f55f55f..
.....f555555f...
......ffffff....
......feeeeef...
.....fefffddff..
....ffeedfffffc.
...fddeed2dd2dc.
...cdbeeddddeedc
ff.cdbeedddddddc
fef.cfeedccccccc
fef..ffeedddddf.
fef.feeeefffff..
feffeeeeeeef....
.ffeeeefeffef...
..feeeefeffef...
...feffbdfbdf...
...fdbbddcddf...
...fffffffff....
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "munkey run":
            case "anim1":return [img`
. . . . . . . f f f f f . . . . 
. . . . . . f e e e e e f . . . 
. . . . . f e e e d d d d f . . 
. . . . f f e e d f d d f d c . 
. . . f d d e e d f d d f d c . 
. . . c d b e e d d d d e e d c 
f f . c d b e e d d c d d d d c 
f e f . c f e e d d d c c c c c 
f e f . . f f e e d d d d d f . 
f e f . f e e e e f f f f f . . 
f e f f e e e e e e e f . . . . 
. f f e e e e f e f f e f . . . 
. . f e e e e f e f f e f . . . 
. . . f e f f b d f b d f . . . 
. . . f d b b d d c d d f . . . 
. . . f f f f f f f f f . . . . 
`, img`
. . . . . . . f f f f f . . . . 
. . . . . . f e e e e e f . . . 
. . . . . f e e e d d d d f . . 
. . . . . f e e d f d d f d c . 
. . . . f f e e d f d d f d c . 
. . . f d d e e d d d d e e d c 
. . . c d b e e d d c d d d d c 
f f . c d b e e e d d c c c c c 
f e f . c f f e e e d d d d f . 
f e f . f e e e e f f f f f f . 
f e f f e e e e e e e f f f f . 
. f f e e e e f e f d d f d d f 
. . f e e e e f e f b d f b d f 
. . f e f f f f f f f f f f f f 
. . f d d c f . . . . . . . . . 
. . f f f f . . . . . . . . . . 
`, img`
. . . . . . . f f f f f . . . . 
. . . . . . f e e e e e f . . . 
. . . . f f e e e d d d d f . . 
. . . f d d e e d d d d d d c . 
. . . c d b e e d f d d f d c . 
f f . c d b e e d f d d f d d c 
f e f . c f e e d d d d e e d c 
f e f . . f e e e d c d d d d c 
f e f . . f f e e e d c c c f . 
f e f . f e e e e f f f f f . . 
. f f f e e e e e e e f . . . . 
. . f e e e e f e e f e f f . . 
. . f e e e f f f e e f f e f . 
. f b f f f f f f c d d b d d f 
. f d d c f . . f d d d c d d f 
. . f f f . . . f f f f f f f . 
`, img`
. . . . . . . f f f f f . . . . 
. . . . f f f e e e e e f . . . 
. . . f d d e e e e d d d f . . 
. . . c d b e e e d d d d d c . 
. . . c d b e e d d d d d d c . 
. f f . c f e e d f d d f d d c 
f e f . . f e e d f d d f d d c 
f e f . . f e e d d d d e e d c 
f e f . . f f e e d c d d d f . 
f e f . f e e e e e d f f f . . 
. f f f e e e e e e e f . . . . 
. . f f b e e e e e f f . . . . 
. . f f d d c e e f f e f . . . 
. . . . f f f c d d b d d f . . 
. . . . . f f d d d c d d f . . 
. . . . . . f f f f f f f . . . 
`, img`
. . . . . . . f f f f f . . . . 
. . . . . . f e e e e e f . . . 
. . . . . f e e e d d d d f . . 
. . . . f f e e d f d d f d c . 
. . . f d d e e d f d d f d c . 
. . . c d b e e d d d d e e d c 
. . . c d b e e d d c d d d d c 
. . . . c f e e e d d c c c c c 
. . . . . f f e e e d d d d f . 
. . . . f e e e e f f f f f . . 
f f . f e e e e e e f f . . . . 
f e . f e e f e e f e e f . . . 
f e . f e e e f e e f e e f . . 
f e f f e f b b f b d f d b f . 
f f f f e b d d f d d f d d f . 
. f f f f f f f f f f f f f . . 
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
